### ISSUE TITLE
DEV版本使用openai的代理地址不可用

### ISSUE THREAD

**Issue by forjustice** [mirrors2/opencatd-open#36]
在docker中，使用了环境变量以添加代理
$CUSTOM_ENDPOINT=true &&  $OpenAI_Endpoint=https://your.domain

添加key后，聊天时提示TEAM错误。

但去除所有环境变量（使用openai默认的host）后，恢复正常使用，

请问下，该环境变量该如何填写呢？谢谢。

**Comment by Sakurasan** [comment]
已更新https://github.com/mirrors2/opencatd-open/tree/dev?tab=readme-ov-file#qa ,只要设置OpenAI_Endpoint就行了
